### PR TITLE
Add Authentication & Authorization Components

### LINKED ISSUE #15: Add Authentication/ Authorization Component
### Authentication

- User authenticated should stay in session
- On successful authentication, he should be allowed to access authorized routes

### Authorization

- User should be allowed to access restricted routes only when he/ she has been authenticated successfully

### PR DESCRIPTION
**Pull request by CajetanRodrigues**
Fix #15 

I have added the component which is concerned with successful authentication and authorization of the user.

It comprises of 
1] Login Component

login

2] SignUp Component

signup

3] Verification Component

verification

4] Forgot Password

forgot

### CODE REVIEW

**Comment by ankit01ojha** [comment]
@CajetanRodrigues , could you just squash these three commits into one.

**Review by ankit01ojha — COMMENTED** [review]
@CajetanRodrigues , could you just squash these three commits into one.

**Comment by CajetanRodrigues** [comment]
> @CajetanRodrigues , could you just squash these three commits into one.

Done

**Comment by ankit01ojha** [comment]
@CajetanRodrigues follow the same form UI design from the web-self-service app.

**Review by ankit01ojha — COMMENTED** [review]
@CajetanRodrigues follow the same form UI design from the web-self-service app and fix the login too.

**Pull request merged**
